### ISSUE TITLE
HA256 mismatch install error

### ISSUE THREAD

**Issue by MikeLP** [smockle/homebrew-iojs#1]
HA256 mismatch
Expected: 0effc6eb79e1b846d2bc917b2d91eb0a5699e0dba3cdcb1ffd3b8e5b970bba62
Actual: a378054d4fd0914c173c38933fcd02822731a76dafa4da5c55d83a954873ba37
Archive: /Library/Caches/Homebrew/iojs-46.tar.gz
To retry an incomplete download, remove the file above.

**Comment by MikeLP** [comment]
New link https://iojs.org/download/nightly/v1.0.0-nightly2015011284fa1f8c46/iojs-v1.0.0-nightly2015011284fa1f8c46-darwin-x64.tar.gz
New sha256 63486322b282c9652afa8ab40959eeeecfadffd368f1dd4ede732d1f4acc882d

**Comment by smockle** [comment]
Thanks for filing this! I just updated the hash. Would you mind updating the formula and then trying to install again? If you still get the error, would you try `rm /Library/Caches/Homebrew/iojs-*.tar.gz` and then `brew install iojs`?

**Comment by mrmurphy** [comment]
Hmm, I just did a brew update, and I'm also getting the SHA mismatch error:

```
brew install iojs
==> Installing iojs from smockle/homebrew-iojs
==> Downloading https://iojs.org/download/nightly/v1.0.0-nightly201501135ea716d895/iojs-v1.0.0-nightly201501135ea
Already downloaded: /Library/Caches/Homebrew/iojs-895.tar.gz
Error: SHA256 mismatch
Expected: f6ac6384910d8aa635f751d880d594c434fb40247a188f3e3fdc6694586f705b
Actual: c412a95bc44197f75293962040cccfbb9a34bb5f47aa8195a413bc163d98108a
Archive: /Library/Caches/Homebrew/iojs-895.tar.gz
To retry an incomplete download, remove the file above.
```

It appears that the new URL isn't getting updated. Or maybe I just don't know how to properly update taps with brew?

**Comment by mrmurphy** [comment]
It looks like your new link doesn't match the link in https://raw.githubusercontent.com/smockle/homebrew-iojs/master/Formula/iojs.rb I think.

**Comment by smockle** [comment]
@murphyrandle Thanks for reporting! I asked about this in the #io.js channel on Freenode, and was told:

```
nightlies have been a place to experiment for me so some of them (perhaps all of them?) have been rebuilt multiple times
```

In other words, the nightly source tarball is being updated, though the version number is kept constant. Each update changes the hash. New hashes will cause a mismatch with the hash in this formula.

We have two options: 1. Fix these as people notice a mismatch (which is inconvenient, but shouldn't be an issue once a stable semver-versioned release is made) or 2. Ignore mismatched hashes (which is less secure).

**Comment by mrmurphy** [comment]
What do you feel inclined to do at this point @smockle?

**Comment by smockle** [comment]
@murphyrandle I'm open to suggestions. I'm leaning towards continuing to fix this as it pops up, since I don't think this will continue to be an issue once multiple builds aren't pushed with the same version number (i.e. once there is a stable release). Which is planned for today, AFAIK.

The plan is to move this formula into homebrew/homebrew: https://github.com/iojs/io.js/issues/298. I'm not sure of the Homebrew policy, but I assume they'd rather we not ignore hashes.

I just asked on IRC, and nightly builds will continue to be pushed to https://iojs.org/download/nightly/ after the stable release. I'd like to have a second formula called "iojs-nightly" that lets anyone try that build via homebrew. The "iojs-nightly" formula may or may not ignore hashes--I'll have to see how often multiple nightly builds are pushed with the same version number then.

**Comment by mrmurphy** [comment]
I think that makes a lot of sense ☺
